"use client";

import React, { useMemo, useState, useCallback, useEffect } from "react";
import { SubAgentIndicator } from "@/app/components/SubAgentIndicator";
import { ToolCallBox } from "@/app/components/ToolCallBox";
import { MarkdownContent } from "@/app/components/MarkdownContent";
import { SuggestedQuestionsRenderer } from "@/app/components/SuggestedQuestionsRenderer";
import { MessageActionBar } from "@/app/components/MessageActionBar";
import type {
  SubAgent,
  ToolCall,
  ActionRequest,
  ReviewConfig,
} from "@/app/types/types";
import { Message } from "@langchain/langgraph-sdk";
import {
  extractSubAgentContent,
  extractStringFromMessageContent,
} from "@/app/utils/utils";
import { cn } from "@/lib/utils";

interface ChatMessageProps {
  message: Message;
  toolCalls: ToolCall[];
  isLoading?: boolean;
  isLastMessage?: boolean;
  actionRequestsMap?: Map<string, ActionRequest>;
  reviewConfigsMap?: Map<string, ReviewConfig>;
  ui?: any[];
  stream?: any;
  onResumeInterrupt?: (value: any) => void;
  graphId?: string;
}

/**
 * Extracts follow-up questions generated by the LLM inside tagged blocks.
 */
function extractFollowUpQuestions(content: string): string[] {
  if (!content) return [];

  // 1. Check for XML tag <follow_up_questions> ... </follow_up_questions>
  const tagMatch = content.match(/<follow_up_questions>([\s\S]*?)<\/follow_up_questions>/i);
  if (tagMatch && tagMatch[1]) {
    const lines = tagMatch[1]
      .split("\n")
      .map((l) => l.replace(/^[-*•\d.↳"\[\]\s]+/, "").replace(/[",\]]/g, "").trim())
      .filter((l) => l.length > 5);
    if (lines.length > 0) return lines.slice(0, 4);
  }

  // 2. Check for ```suggestions or ```followup code blocks
  const codeMatch = content.match(/```(?:suggestions|suggestion|followup|follow_up_questions|questions)\s*([\s\S]*?)\s*```/i);
  if (codeMatch && codeMatch[1]) {
    try {
      const parsed = JSON.parse(codeMatch[1].trim());
      if (Array.isArray(parsed) && parsed.length > 0) {
        return parsed.map((s) => String(s).trim()).filter(Boolean);
      }
    } catch {
      const lines = codeMatch[1]
        .split("\n")
        .map((l) => l.replace(/^[-*•\d.↳"\[\]\s]+/, "").replace(/[",\]]/g, "").trim())
        .filter((l) => l.length > 5);
      if (lines.length > 0) return lines.slice(0, 4);
    }
  }

  // 3. Check for Markdown header "### 💡 Câu Hỏi Gợi Ý" or "### Gợi ý câu hỏi"
  const headerMatch = content.match(/(?:###|\*\*|💡)?\s*(?:Câu Hỏi Gợi Ý|Gợi ý câu hỏi|Follow-up Questions)[^\n]*\n([\s\S]*?)(?:\n\n[#*]|\n---|$)/i);
  if (headerMatch && headerMatch[1]) {
    const lines = headerMatch[1]
      .split("\n")
      .map((l) => l.replace(/^[-*•\d.↳]\s*/, "").trim())
      .filter((l) => l.length > 6);
    if (lines.length > 0) return lines.slice(0, 4);
  }

  return [];
}

/**
 * Trims out the tagged follow-up question section from the main response body
 * so it is not rendered twice as raw markdown text.
 */
function trimFollowUpSection(content: string): string {
  if (!content) return "";
  return content
    .replace(/<follow_up_questions>[\s\S]*?<\/follow_up_questions>/gi, "")
    .replace(/```(?:suggestions|suggestion|followup|follow_up_questions|questions)[\s\S]*?```/gi, "")
    .replace(/(?:###|\*\*|💡)?\s*(?:Câu Hỏi Gợi Ý|Gợi ý câu hỏi|Follow-up Questions)[^\n]*\n([\s\S]*?)(?:\n\n[#*]|\n---|$)/gi, "")
    .trim();
}

export const ChatMessage = React.memo<ChatMessageProps>(
  ({
    message,
    toolCalls,
    isLoading,
    isLastMessage = true,
    actionRequestsMap,
    reviewConfigsMap,
    ui,
    stream,
    onResumeInterrupt,
    graphId,
  }) => {
    const isUser = message.type === "human";
    const rawMessageContent = extractStringFromMessageContent(message);
    const hasContent = rawMessageContent && rawMessageContent.trim() !== "";
    const hasToolCalls = toolCalls.length > 0;

    // 1. Direct tag-based questions from response (only extracted when stream finishes)
    const tagQuestions = useMemo(() => {
      if (isUser || !hasContent || isLoading) return [];
      return extractFollowUpQuestions(rawMessageContent);
    }, [isUser, hasContent, isLoading, rawMessageContent]);

    // 2. Real-time LLM-generated questions fallback if not embedded in response
    const [apiQuestions, setApiQuestions] = useState<string[]>([]);

    useEffect(() => {
      if (isUser || !hasContent || !isLastMessage || isLoading || tagQuestions.length > 0) {
        return;
      }

      let isMounted = true;
      const fetchFollowUps = async () => {
        try {
          const res = await fetch("/api/generate-followups", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ content: rawMessageContent }),
          });
          if (res.ok) {
            const data = await res.json();
            if (isMounted && Array.isArray(data.questions) && data.questions.length > 0) {
              setApiQuestions(data.questions);
            }
          }
        } catch (e) {
          console.error("Failed to generate follow-up questions:", e);
        }
      };

      fetchFollowUps();
      return () => {
        isMounted = false;
      };
    }, [isUser, hasContent, isLastMessage, isLoading, tagQuestions.length, rawMessageContent]);

    const finalQuestions = useMemo(() => {
      if (tagQuestions.length > 0) return tagQuestions;
      return apiQuestions;
    }, [tagQuestions, apiQuestions]);

    // Trim the tagged follow-up section from main response markdown (only after stream completes)
    const trimmedContent = useMemo(() => {
      if (!hasContent) return "";
      if (isLoading) return rawMessageContent;
      return trimFollowUpSection(rawMessageContent);
    }, [rawMessageContent, hasContent, isLoading]);

    const subAgents = useMemo(() => {
      return toolCalls
        .filter((toolCall: ToolCall) => {
          return (
            toolCall.name === "task" &&
            toolCall.args["subagent_type"] &&
            toolCall.args["subagent_type"] !== "" &&
            toolCall.args["subagent_type"] !== null
          );
        })
        .map((toolCall: ToolCall) => {
          const subagentType = (toolCall.args as Record<string, unknown>)[
            "subagent_type"
          ] as string;
          return {
            id: toolCall.id,
            name: toolCall.name,
            subAgentName: subagentType,
            input: toolCall.args,
            output: toolCall.result,
          };
        });
    }, [toolCalls]);

    const [expandedSubAgents, setExpandedSubAgents] = useState<
      Record<string, boolean>
    >({});

    const toggleSubAgent = useCallback((id: string) => {
      setExpandedSubAgents((prev) => ({
        ...prev,
        [id]: !prev[id],
      }));
    }, []);

    const isSubAgentExpanded = useCallback(
      (id: string) => {
        return expandedSubAgents[id] ?? false;
      },
      [expandedSubAgents]
    );

    // If human message: Render User Bubble
    if (isUser) {
      return (
        <div className="flex w-full justify-end my-3">
          <div className="max-w-[85%] rounded-2xl rounded-tr-sm bg-gradient-to-tr from-[#0E1538] to-[#162055] border border-[#00FF88]/30 px-4 py-3 text-sm text-white shadow-[0_0_15px_rgba(0,255,136,0.15)] leading-relaxed">
            <p className="whitespace-pre-wrap font-medium">{rawMessageContent}</p>
          </div>
        </div>
      );
    }

    // For AI messages: Render Subagents -> Tool Calls -> Trimmed Markdown Content -> Follow-Up Question UI (Last response only)
    return (
      <div className="flex w-full max-w-full overflow-x-hidden my-2">
        <div className="min-w-0 w-full flex flex-col gap-2">
          {/* 1. Sub-Agents (if any) */}
          {subAgents.length > 0 && (
            <div className="flex w-fit max-w-full flex-col gap-3">
              {subAgents.map((subAgent) => (
                <div
                  key={subAgent.id}
                  className="flex w-full flex-col gap-2"
                >
                  <div className="flex items-end gap-2">
                    <div className="w-[calc(100%-100px)]">
                      <SubAgentIndicator
                        subAgent={subAgent}
                        onClick={() => toggleSubAgent(subAgent.id)}
                        isExpanded={isSubAgentExpanded(subAgent.id)}
                      />
                    </div>
                  </div>
                  {isSubAgentExpanded(subAgent.id) && (
                    <div className="w-full max-w-full">
                      <div className="bg-[#0E1538] border-[#00FF88]/20 rounded-xl border p-4 shadow-[0_0_15px_rgba(0,255,136,0.1)]">
                        <h4 className="text-[#00FF88] mb-2 text-xs font-semibold uppercase tracking-wider">
                          Dữ Liệu Đầu Vào Của Sub-Agent
                        </h4>
                        <div className="mb-4 text-xs text-[#94A3B8]">
                          <MarkdownContent
                            content={extractSubAgentContent(subAgent.input)}
                          />
                        </div>
                        {subAgent.output && (
                          <>
                            <h4 className="text-[#00D2FF] mb-2 text-xs font-semibold uppercase tracking-wider">
                              Thông Tin Phân Tích Của Sub-Agent
                            </h4>
                            <div className="text-xs text-[#94A3B8]">
                              <MarkdownContent
                                content={extractSubAgentContent(subAgent.output)}
                              />
                            </div>
                          </>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}

          {/* 2. Tool Calls Display */}
          {hasToolCalls && (
            <div className="flex w-full flex-col gap-2">
              {toolCalls.map((toolCall: ToolCall) => {
                if (toolCall.name === "task") return null;
                const toolCallGenUiComponent = ui?.find(
                  (u) => u.metadata?.tool_call_id === toolCall.id
                );
                const actionRequest = actionRequestsMap?.get(toolCall.name);
                const reviewConfig = reviewConfigsMap?.get(toolCall.name);
                return (
                  <ToolCallBox
                    key={toolCall.id}
                    toolCall={toolCall}
                    uiComponent={toolCallGenUiComponent}
                    stream={stream}
                    graphId={graphId}
                    actionRequest={actionRequest}
                    reviewConfig={reviewConfig}
                    onResume={onResumeInterrupt}
                    isLoading={isLoading}
                  />
                );
              })}
            </div>
          )}

          {/* 3. Final Trimmed Response Content */}
          {hasContent && (
            <div className="relative flex flex-col w-full mt-2">
              <div className="overflow-hidden break-words text-sm font-normal leading-relaxed text-white w-full">
                <MarkdownContent
                  content={trimmedContent}
                  isStreaming={isLoading && isLastMessage}
                />
                
                {/* 4. Follow-Up Questions rendered in clean ↳ UI (Last response only) */}
                {isLastMessage && !isLoading && finalQuestions.length > 0 && (
                  <SuggestedQuestionsRenderer questions={finalQuestions} />
                )}

                {/* 5. Message Quick Action Bar (Copy Report, Download CSV, Feedback) */}
                {!isLoading && (
                  <MessageActionBar content={trimmedContent} />
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    );
  }
);

ChatMessage.displayName = "ChatMessage";
